Closes #131 - featured team on userprofile
NFM-Studios/project-olly pull request #139
Opened 2021-04-29 23:03 UTC by mikemaddem

2021-04-30 23:41 UTC, dannygreg requested changes
Only a couple nits really.

2021-04-30 23:41 UTC, dannygreg commented on profiles/forms.py
> +        # super(EditProfileForm, self).__init__(*args, **kwargs)
Should probably remove this commented out code.

2021-04-30 23:41 UTC, dannygreg commented on profiles/models.py
> +    feat_team = models.ForeignKey('teams.Team', related_name='profile_feat_team', blank=True, null=True, on_delete=models.SET_NULL)
It's a nitpick - but I don't usually like abbreviated variable names. We don't pay-by-the-byte these days so may as well make it `featured_team`.

2021-05-06 19:13 UTC, mikemaddem commented
@dannygreg  @techlover1 Changes made

2021-05-07 20:22 UTC, merged